name: Elysium_Bosses
version: '${project.version}'
main: dev.huls.elysium_bosses.Main
api-version: '1.20'
commands:
  giveboss:
    description: Give a boss egg
    usage: /giveboss <player>
    permission: elysium.bosses.give
